package com.example.administrator.webviewpagescannerapp;

import android.util.Log;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Created by Administrator on 2017/2/9.
 */

public class StringUtils {
    public static String [] returnImageUrlsFromHtml() {
        List<String> imageSrcList = new ArrayList<String>();
        String htmlCode = returnExampleHtml();
        Pattern p = Pattern.compile("<img\\b[^>]*\\bsrc\\b\\s*=\\s*('|\")?([^'\"\n\r\f>]+(\\.jpg|\\.bmp|\\.eps|\\.gif|\\.mif|\\.miff|\\.png|\\.tif|\\.tiff|\\.svg|\\.wmf|\\.jpe|\\.jpeg|\\.dib|\\.ico|\\.tga|\\.cut|\\.pic)\\b)[^>]*>", Pattern.CASE_INSENSITIVE);
        Matcher m = p.matcher(htmlCode);
        String quote = null;
        String src = null;
        while (m.find()) {
            quote = m.group(1);
            src = (quote == null || quote.trim().length() == 0) ? m.group(2).split("//s+")[0] : m.group(2);
            imageSrcList.add(src);
        }
        Log.e("imageUrls",imageSrcList.get(0).toString());
        return imageSrcList.toArray(new String[imageSrcList.size()]);
    }


    public static String returnExampleHtml(){

        return "<style>html, body{ width: 100%;height: 100%; font-size: 10px;}#section_projectDetail{}#section_projectDetail .section_project_title{ height:3rem; line-height:3rem; border-bottom:1px #ddd solid; text-indent:1rem; font-size:1.6rem; color:#808080;}#section_projectDetail img{ max-width:100%;}#section_projectDetail .section_project_content{padding:1rem; line-height:2rem; color:#666; font-size:1.4rem;}#section_projectDetail .section_project_content p{ padding:.4rem 0;}embed,video{ max-width:100%; height:auto;}</style><section id=\"section_projectDetail\"><div class=\"section_project_title\">项目背景</div><div class=\"section_project_content\"><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><strong>　　政策性变动及应对策略</strong></span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\"; color: rgb(192, 0, 0);\">　　<strong>背景说明：</strong>　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　作为中X资本控股国内的核心业务平台，中X资本股权投资(天津)股份有限公司(“中X资本(天津)”)原计划于2015年底登陆全国中小企业股份转让系统同时实行定向增发，募集收购母公司优质海外基金的LP权益并开展在境内的各项私募股权投资管理业务。但是在2015年底，证券会宣布暂停PE机构在新三板挂牌，由此带来的政策性变动导致了企业挂牌中断。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\"; color: rgb(192, 0, 0);\">　　<strong>应对策略：</strong>　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><strong>　　坚定看好国内市场，坚持原有发展战略</strong></span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　基于对国内市场的坚定信心，以及中X资本回归国内市场的决心，中X资本维持原有战略不变，继续投入大量的精力及资源把中X资本(天津)打造为中X资本的人民币平台，做强、做大业务。　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　<span style=\"font-family: 微软雅黑, \"Microsoft YaHei\"; color: rgb(192, 0, 0);\">中X资本(天津)定位为中X资本控股的“窗口公司”，也是中X资本“境内唯一人民币私幕股权投资管理平台”</span>，境内投资者可直接通过中X资本(天津)投资于中X资本发行的境内境外基金以及中X资本优质项目。对于打算与中X资本进行合作的现有或潜在境内投资者而言，这将为境内投资者开辟了一个更为便捷的投资渠道，更优化的投资方式，并有利于提供更加丰富及广泛的合作机会。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><strong>　　股东注资，完成资产注入</strong>　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　中X资本控股即将用25亿人民币的自有资金把中X资本管理的优质资产<strong>(中X资本所投资自身管理基金的美元LP份额)</strong>注入中X资本（天津），在收购后完成2015年融资计划承诺。　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　" +
                "　本轮所有投资款将全部投入新项目投资以及人民币平台业务的打造，不会承担资产注入不成功的风险。因此，本轮投资者可以享受注入美元基金资产带来的基础投资收益的同时，分享挂牌公司未来成长收益。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><strong>　　首轮募集，强势股东站台　</strong>　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　在资产注入后，完成首轮私募股权融资，引入腾讯、中X信托等其他知名外部战略投资者。强势股东的站台为中X资本（天津）提供了强大的信用背书，同时为公司未来登录新三板市场打下资本及业务资源基础。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　<strong>成立国际及国内基金，顺利开展业务　　</strong></span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　2016年，中X资本对境内境外基金业务做进一步的布局。首先，中X资本先后成立了美元中国私募并购基金三号（CITIC Capital China Partners Ⅲ）、日本私募并购基金三号（CITIC Capital Japan Partners Ⅲ）和一带一路基金一号（CITIC Capital Silk Road Fund），<span style=\"font-family: 微软雅黑, \"Microsoft YaHei\"; color: rgb(192, 0, 0);\">上述的基金在境外募集时均取得非常好的反响，额度供不应求，境内外著名机构均参与墓集。其中投资者不乏著名国际金融机构投资者（包括退休基金、保险公司等等）</span>。另外，中X资本在国内即将成立一系列的人民币基金产品，配合国内的大环境，成立专项投资基金，投资领域包括电商、物流、医疗、文化等等。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　中X资本过去14年在海外市场取得了有目共睹的投资业绩，成立之初就有一个标准的海归团队，并且<span style=\"font-family: 微软雅黑, \"Microsoft YaHei\"; color: rgb(192, 0, 0);\">在美国、日本等国家都拥有自己的投资团队，这些经验丰富的跨境专业项目团队</span>，积累了大量的优质海外项目储备及资源。<span style=\"font-family: 微软雅黑, \"Microsoft YaHei\"; color: rgb(192, 0, 0);\">另外中X资本会将在近期进一步开拓美国市场，推进平台整合的项目</span>。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　而中X资本(天津)对中X资本发行的海内外基金均具有优先认购权，优先于境内外投资者投资于优质基金，享受中X资本的投资资源及红利。在目前全球化的经济形势下，具备独一无二的全球投资能力的中X资本和作为母公司的人民币平台的中X资本(天津)，将共同全力打造双币种的海外资产配置双平台，为投资者提供独特的投资机会。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><br/></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><strong>　　全球私募股权投资行业发展现状及趋势</strong></span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"color: rgb(192, 0, 0); font-family: 微软雅黑, \"Microsoft YaHei\";\"><strong>　　全球股权投资市场随着资产管理行业的发展应运而生</strong>　　" +
                "</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　宏观经济稳定增长及货币供给加速带来了财富的不断积累，各国利率的持续走低刺激了资金的配置需求，这些因素驱动了资产管理行业的蓬勃发展。全球资产管理行业规模在2014年达到了74万亿美元这一新的记录。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　私募股权投资起源于20世纪40年代的美国，在2005年至2007年间，私募股权投资行业成交量巨大。2008年全球金融危机使得私募股权投资行业陷入低迷。经历了七年的经济动荡，2014年全球资本市场开始复苏，稳健的公司利润实现和股票市场的反弹等条件为私募股权投资的资产价值实现铺平了道路。</span></p><p><br/></p><p style=\"text-align: center;\"><img src=\"http://img1.zczj.com/images/20170109/20170109154702.png\" title=\"YYPDF截图201719154512.png\" alt=\"YYPDF截图201719154512.png\"/></p><p><br/></p></div></section><section id=\"section_projectDetail\"><div class=\"section_project_title\">标的项目介绍</div><div class=\"section_project_content\"><p><span style=\"color: rgb(192, 0, 0);\"><strong><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　标的概况：　　</span></strong></span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　中X资本(天津)成立于2009年1月23日，是中X资本控股在中国境内打造的核心基金投资和管理业务平台。中X资本控股承诺，本公司将作为中X资本控股在中国境内(不含香港)开展私募股权投资和管理的核心业务平台。公司旗下的母基金有权优先认购中X资本控股在境内外发起设立的基金项目，从而保证公司有权分享中X资本控股在境内外优秀项目的投资收益，为境内投资者分享中X资本控股卓越的投资能力提供了可靠的渠道。此外，公司在本轮私募股权融资前，中X资本控股将向本公司注入约人民币30亿元的境内外优质LP基金投资份额后，收购后将会确保公司股东以及管理基金的投资者能够分享中X资本控股在境内外的投资收益。　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　中X资本(天津)是中X资本控股在境内打造的母基金投资管理平台，并正在打造以母基金业务、多方向人民币私幕股权投资基金业务和一带一路基金业务为主的业务架构，参与中X资本控股的各个项目。公司基于产业链完整、布局合理的业务模式，提供专业化、综合化、结构化金融解决方案，满足不同类型客户的风险偏好和投资诉求，在给被投资企业输入资本的同时，也充分利用自身和实际控制人的业务和资源优势，全面提升被投资企业的战略发展水平。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><strong><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\"; color: rgb(192, 0, 0);\">　　标的发展路径：　　</span></strong></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　中X资本控股通过在国内设立中X资本股权投资（天津）股份有限公司为融资主体，打造中国境内核心的人民币私募股权投资和管理业务平台，完成对国内资本市场业务的全面布局。</span></p><p><br/></p><p style=\"text-align: center;\"><img src=\"http://img1.zczj.com/images/20170109/20170109165156.png\" title=\"YYPDF截图201719155535.png\" alt=\"YYPDF截图201719155535.png\" width=\"790\" height=\"412\" border=\"0\" vspace=\"0\" style=\"width: 790px; height: 412px;\"/></p><p><br/></p><p><strong><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";" +
                " color: rgb(192, 0, 0);\">　　业务模式：　</span></strong></p><p style=\"text-align: center;\"><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><img src=\"http://img1.zczj.com/images/20170109/20170109165212.png\" title=\"YYPDF截图201719155629.png\" alt=\"YYPDF截图201719155629.png\"/>　</span></p><p><strong><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\"; color: rgb(192, 0, 0);\">　　投资模式介绍：</span></strong></p><p style=\"text-align: center;\"><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><img src=\"http://img1.zczj.com/images/20170109/20170109165229.png\" title=\"YYPDF截图201719155844.png\" alt=\"YYPDF截图201719155844.png\"/>　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　其中一带一路基金仅哈萨克斯坦“中X卡森纳直接投资基金”规模近14.5亿美金，另一只中东一带一路投资基金近5亿美金，预计到2017年底，一带一路基金共计50亿美金。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><strong><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\"; color: rgb(192, 0, 0);\">　　标的资本投资逻辑：　　</span></strong></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　● 作为拥有“国家队’背景的中X资本控股是国际PE投资机构，公司本次在国内设立核心资本运作平台，旨在全面参与中国境内资本市场变革，充分把握未来3~5年国内资产管理行业发展的黄金机遇。　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　<span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">● </span>公司已经注入了海外优质资产，并构建了以“母基金、私募股权基金，一带一路基金”为核心的业务模式，依托客户及项目资源，做大做强境内资产管理业务，逐步开展高端理财业务，向则富管理业务延展，最终打造国内首屈一指的综合性资产管理机构。　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　<span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">●</span> 中X资本控股拥有大中华地区独一无二的全球投资能力，借助海外14年发展建立的多元化投资网络以及丰富的跨境专业团队经验，取得了优异的投资收益。当前经济形势下，海外优质项目是国内投资者极佳的资产配且选择。中X资本控股目前仍有大量优质海外项目储备，具有较大的增值潜力。本次回归国内发展，投资者可以借助公司核心资产注入的交易契机，享受成为国际顶级PE机构权益拥有者的机会。</span></p><p><br/></p></div></section><section id=\"section_projectDetail\"><div class=\"section_project_title\">投资业绩</div><div class=\"section_project_content\"><p><strong><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\"; color: rgb(192, 0, 0);\">　　享受中X资本控股出色的投资业绩：</span></strong></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　依托于强大的股东背景、广泛的投资者覆盖和卓越的投资管理能力，中X资本控股在各个领域都取得了出众的投资业绩。</span></p><p style=\"text-align: center;\"><img src=\"http://img1.zczj.com/images/20170109/20170109160730.png\" title=\"YYPDF截图20171916545.png\" alt=\"YYPDF截图20171916545.png\"/></p><p><span style=\"font-family: 微软雅黑, \"M" +
                "icrosoft YaHei\";\"><br/></span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><br/></span></p><p><strong><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\"; color: rgb(192, 0, 0);\">　　资产注入：2015年6月，注资4.34亿，完成首批人民币私募股权投资基金LP份额</span></strong></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　● 2015年6月，中X资本出资4.34亿元收购了人民币私募股权基金月10%的有限合伙权益；　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　● 该基金目前在投项目10余个，其中的股权投资项目标的均为经营业绩良好、市场地位领先的优质企业，上述项目退出后，预计将为公司带来丰厚的投资收益，其中代表性项目如下：</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><br/></span></p><p style=\"text-align: center;\"><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><img src=\"http://img1.zczj.com/images/20170109/20170109160805.png\" title=\"YYPDF截图20171916627.png\" alt=\"YYPDF截图20171916627.png\"/></span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"color: rgb(192, 0, 0);\"><strong><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　资产注入：2016年4月，注资25亿，完成海外投资基金LP份额受让</span></strong></span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><br/></span></p><p style=\"text-align: center;\"><img src=\"http://img1.zczj.com/images/20170109/20170109165249.png\" title=\"YYPDF截图2017191675.png\" alt=\"YYPDF截图2017191675.png\"/></p><p style=\"text-align: center;\"><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p style=\"text-align: center;\"><strong><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">中X资本控股旗下基金基本情况概览</span></strong></p><p><strong><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><br/></span></strong></p><p style=\"text-align: center;\"><strong><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><img src=\"http://img1.zczj.com/images/20170109/20170109165258.png\" title=\"YYPDF截图20171916759.png\" alt=\"YYPDF截图20171916759.png\"/></span></strong></p><p><br/></p></div></section><section id=\"section_projectDetail\"><div class=\"section_project_title\">行业对比</div><div class=\"section_project_content\"><p style=\"text-align: center;\"><img src=\"http://img1.zczj.com/images/20170109/20170109163153.png\" title=\"YYPDF截图201719161856.png.png\" alt=\"YYPDF截图201719161856.png.png\" width=\"790\" height=\"417\" border=\"0\" vspace=\"0\" style=\"width: 790px; height: 417px;\"/></p></div></section><section id=\"section_projectDetail\"><div class=\"section_project_title\">财务数据</div><div class=\"section_project_content\"><p style=\"text-align: center;\"><img src=\"http://img1.zczj.com/images/20170109/20170109165319.png\" title=\"YYPDF截图201719162029.png\" alt=\"YYPDF截图201719162029.png\"/></p><p><br/></p><p style=\"text-align: center;\"><img src=\"http://img1.zczj.com/images/20170109/20170109162457.png\" title=\"YYPDF截图201719162049.png\" " +
                "alt=\"YYPDF截图201719162049.png\"/></p></div></section><section id=\"section_projectDetail\"><div class=\"section_project_title\">投资亮点</div><div class=\"section_project_content\"><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　<strong>1、强大的股东背景：</strong>股东包括中X集团、腾讯控股、中X信托、卡塔尔控股（管理中东主权基金）、信达资产、国安集团等。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　<strong>2、出众的投资业绩：</strong>2002成立至今管理规模180亿美元，股权基金平均收益回报2~6倍，各投资业务领域都取得出众投资业绩，如：阿里巴巴、顺丰速运、昆仑万维、分众传媒、步长制药、豪威科技、麦当劳（亚洲）、TCL、哈药股份、亚信联创、中投保、信达资产、桂发祥、常熟汽饰等等。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　<strong>3、卓越的投资团队：</strong>管理团队历经14年打造，具备大中华地区最强的全球跨境投资能力、最强的境内外产业整合投资经验和良好的投资管理业绩，同时还具有深厚的境内外社会资源。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　<strong>4、丰富的优质项目资源：</strong>依托强劲的股东背景和国际化的精英投资团队，获取大量优质的项目资源，并与腾讯、顺丰、万科等大型产业龙头公司合作产业基金；拥有中X国科(资产管理牌照)和北美、亚太、中东、中亚、欧洲优质项目源。</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　<strong>5、权威的资金来源。</strong>　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　境内LP资源包括：社保基金、国开行、中投公司、信达资产、中X信托、中国建投、中银集团等；　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　境外LP资源包括：安联保险、淡马锡控股、摩根士丹利、日本开发银行、澳洲退休基金、中东主权财富基金、加拿大养老基金等100多家顶级机构。</span></p><p><br/></p></div></section><section id=\"section_projectDetail\"><div class=\"section_project_title\">投资方案</div><div class=\"section_project_content\"><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　<strong>本轮募资用途：</strong>本次募集资金拟用于补充流动资金、后续业务发展及跟投新设基金，以及进一步打造公司的母基金等核心业务平台　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　<strong>投前估值：</strong>120亿元　　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　<strong>管理费：</strong>每年2%（价内）　　</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　<strong>业绩报酬：</strong>超过8%（单利）后，对整体收益收取20%浮动业绩报酬。</span></p><p><br/></p><p style=\"text-align: center;\"><img src=\"http://img1.zczj.com/images/20170109/20170109180910.jpg\" title=\"20160907175302_副本.jpg\" alt=\"20160907175302_副本.jpg\"/></p><p><span style=\"font-family: 微软雅黑, " +
                "\"Microsoft YaHei\";\"><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span><strong>项目退出：</strong></span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span>新三板退出：</span><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">目前已收到“股转系统”二次反馈，预计2017年一季度挂牌新三板；</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span>转让：</span><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">或可能通过股权转让的方式退出；</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span>上市公司并购退出：</span><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">或可能通过将标的公司资产注入到上市公司的方法实现基金退出；</span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">　　</span>转板：</span><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">标的公司计划2018年第二季度启动主板上市工作；</span></p><p><br/></p></div></section><section id=\"section_projectDetail\"><div class=\"section_project_title\">风险提示</div><div class=\"section_project_content\"><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\"></span></p><p><span style=\"font-family: 微软雅黑, 'Microsoft YaHei';\"><span style=\"font-family: 微软雅黑, 'Microsoft YaHei';\">       </span><strong>项目风险：</strong></span></p><p><span style=\"font-family: 微软雅黑, 'Microsoft YaHei';\"><span style=\"font-family: 微软雅黑, 'Microsoft YaHei';\">       </span>1.因政策变化，导致资本运作计划的延迟，没法在封闭期内，上得了资本市场。<br/></span></p><p><span style=\"font-family: 微软雅黑, 'Microsoft YaHei';\"><span style=\"font-family: 微软雅黑, 'Microsoft YaHei';\">       </span>2.因二级市场流动性问题，导致在封闭期内没法及时退出或者退出时跌破增发价。<br/></span></p><p><span style=\"font-family: 微软雅黑, 'Microsoft YaHei';\"><span style=\"font-family: 微软雅黑, 'Microsoft YaHei';\">       </span>3.其他的不可控的未知因素。<br/></span></p><p><br/></p><p><span style=\"font-family: 微软雅黑, 'Microsoft YaHei';\"><span style=\"font-family: 微软雅黑, 'Microsoft YaHei';\">       </span><strong>大股东平台风险提示：</strong></span></p><p><span style=\"font-family: 微软雅黑, \"Microsoft YaHei\";\">       大股东平台所有项目均经过风控团队严格审核，保证项目真实存在，但不能保证项目不存在其他潜在风险，亦不保证项目收益；投资有风险，投资人需根据自身的风险承受能力，选择合适的标的进行投资。</span></p></div></section>";
    }
}
